---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[lucee::default]
    attributes:
      java:
        jdk_version: "8"
      railo:
        major_version: "5"
        minor_version: "0"
